name: login_register_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0  # Replace with the latest version
  firebase_auth: ^4.8.0   # Replace with the latest version
  cloud_firestore: ^4.9.0 # Replace with the latest version
  #firebase_analytics: ^11.9.0 # Replace with the latest version
  water_drop_nav_bar: ^2.2.2
  google_maps_flutter: ^2.2.1
  geolocator: ^10.0.1
  google_sign_in: ^6.0.0
  flutter_launcher_icons: "^0.9.2"

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  spider: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_rm.png"

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
